<?php

$this->headTitle(
    $title = $this->translate( 'search.results.title', 'search' )
);

$this->form
     ->setAttribute( 'action', '?' )
     ->prepare();

?>
<div class="search">
    <h3><?= $this->escapeHtml( $title ) ?></h3>
    <?= $this->form()->openTag( $this->form ) ?>

        <?= $this->form()->renderFieldset( $this->form, 'search-form-elements' ) ?>

<?php if ( ! empty( $this->query ) ): ?>

        <div class="search-results">
<?php if ( empty( $this->results ) ):?>

            <p class="warn no-search-result">
                <?= $this->translate( 'search.results.empty', 'search' ) ?>

            </p>
<?php else: ?>
<?php foreach ( $this->results as $result ):
    $url        = $result->url;
    $relevance  = round( $result->rank * 100 ); ?>

            <div class="search-result">
                <div class="search-result-relevance relevance-<?=
                     str_pad( round( $relevance / 10 ), 2, '0', STR_PAD_LEFT ) ?>"
                     data-relevance="<?= $relevance ?>">
                    <?= $relevance ?>%
                </div>
                <h3 class="search-result-title">
                    <a href="<?= $this->escapeHtmlAttr( $url ) ?>"><?=
                        $this->escapeHtml( $result->title )
                    ?></a>
                </h3>
                <p class="search-result-link">
                    <a href="<?= $this->escapeHtmlAttr( $url ) ?>"><?=
                        $this->escapeHtml( $url )
                    ?></a>
                </p>
                <div class="search-result-headline">
                    <?= htmlspecialchars( $result->headline, ENT_QUOTES ) ?>
                </div>
            </div>
<?php endforeach ?>
<?php endif ?>
<?php endif ?>

        </div>
    <?= $this->form()->closeTag() ?>

</div>
