<?php

$this->headTitle(
    $title = $this->translate( 'search.results.title', 'search' )
);

$this->headLink()
     ->appendStylesheet( '/styles/modules/Search/results.css', 'all' );

$this->form
     ->setAttribute( 'action', '?' )
     ->prepare();

?>
<div class="paragraph-like search">
    <h3><?= $this->escapeHtml( $title ) ?></h3>
    <?= $this->form()->openTag( $this->form ) ?>

        <?= $this->form()->renderFieldset( $this->form, 'search-form-elements' ) ?>

<?php if ( ! empty( $this->query ) ): ?>

        <div class="search-results">
<?php if ( empty( $this->results ) ):?>

            <p class="warn no-search-result">
                <?= $this->translate( 'search.results.empty', 'search' ) ?>

            </p>
<?php else: ?>
<?php foreach ( $this->results as $result ):
    $url        = $result->url;
    $relevance  = round( $result->rank * 100 ); ?>

            <div class="search-result">
                <div class="search-result-relevance relevance-<?= round( $relevance / 10 ) ?>"
                     data-relevance="<?= $relevance ?>">
                    <?= $relevance ?>%
                </div>
                <h4 class="search-result-title">
                    <a href="<?= $this->escapeHtmlAttr( $url ) ?>"><?=
                        $this->escapeHtml( $result->title )
                    ?></a>
                </h4>
                <p class="search-result-link">
                    <a href="<?= $this->escapeHtmlAttr( $url ) ?>"><?=
                        $this->escapeHtml( $url )
                    ?></a>
                </p>
                <div class="search-result-headline">
                    <?= $result->headline ?>

                </div>
            </div>
<?php endforeach ?>
<?php endif ?>
<?php endif ?>

        </div>
    <?= $this->form()->closeTag() ?>

</div>
