-- drop triggers

DROP TRIGGER "1000_search_update_vector" ON "search" CASCADE;
DROP FUNCTION "search_update_vector_trigger"() CASCADE;

-- drop functions

DROP FUNCTION "search_suggestion"(
    CHARACTER VARYING,
    CHARACTER VARYING,
    CHARACTER VARYING,
    BOOLEAN,
    INTEGER,
    INTEGER,
    INTEGER,
    CHARACTER VARYING
) CASCADE;

DROP FUNCTION "search_result_count"(
    CHARACTER VARYING,
    CHARACTER VARYING,
    CHARACTER VARYING,
    BOOLEAN,
    INTEGER,
    INTEGER
) CASCADE;

DROP FUNCTION "search_result"(
    CHARACTER VARYING,
    CHARACTER VARYING,
    CHARACTER VARYING,
    BOOLEAN,
    INTEGER,
    INTEGER,
    INTEGER,
    INTEGER,
    BOOLEAN,
    FLOAT,
    FLOAT,
    FLOAT,
    FLOAT,
    INTEGER,
    CHARACTER VARYING,
    CHARACTER VARYING,
    INTEGER,
    INTEGER,
    INTEGER,
    INTEGER,
    CHARACTER VARYING
) CASCADE;

DROP FUNCTION "search_update"(
    INTEGER,
    CHARACTER VARYING,
    CHARACTER VARYING,
    CHARACTER VARYING,
    CHARACTER VARYING,
    TEXT
) CASCADE;

DROP FUNCTION "search_content_update"(
    CHARACTER VARYING,
    INTEGER,
    BOOLEAN,
    TIMESTAMP WITH TIME ZONE,
    TIMESTAMP WITH TIME ZONE,
    BOOLEAN,
    INTEGER ARRAY,
    INTEGER ARRAY
) CASCADE;

-- drop tables

DROP TABLE "search" CASCADE;
DROP TABLE "search_content" CASCADE;
